/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdSwipe: typeof import('./src/components/AdSwipe.vue')['default']
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppTabbar: typeof import('./src/components/AppTabbar.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    ChannelTab: typeof import('./src/components/ChannelTab.vue')['default']
    CommentDrawer: typeof import('./src/components/douyin/CommentDrawer.vue')['default']
    CommentPanel: typeof import('./src/components/CommentPanel.vue')['default']
    CommentRow: typeof import('./src/components/CommentRow.vue')['default']
    CoverMosaic: typeof import('./src/components/CoverMosaic.vue')['default']
    DouyinFeed: typeof import('./src/components/douyin/DouyinFeed.vue')['default']
    DouyinGrid: typeof import('./src/components/douyin/DouyinGrid.vue')['default']
    DouyinHome: typeof import('./src/components/douyin/DouyinHome.vue')['default']
    EncryptedImage: typeof import('./src/components/EncryptedImage.vue')['default']
    FloorBlock: typeof import('./src/components/home/FloorBlock.vue')['default']
    HlsPlayer: typeof import('./src/components/HlsPlayer.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader.vue')['default']
    HomeHero: typeof import('./src/components/home/HomeHero.vue')['default']
    LineIcon: typeof import('./src/components/LineIcon.vue')['default']
    MediaGrid: typeof import('./src/components/MediaGrid.vue')['default']
    NoticeMarquee: typeof import('./src/components/home/NoticeMarquee.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PosterCard: typeof import('./src/components/home/PosterCard.vue')['default']
    PosterGrid: typeof import('./src/components/home/PosterGrid.vue')['default']
    PosterRail: typeof import('./src/components/home/PosterRail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionPanel: typeof import('./src/components/SectionPanel.vue')['default']
    ShareSheet: typeof import('./src/components/douyin/ShareSheet.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
