/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdSwipe: typeof import('./src/components/AdSwipe.vue')['default']
    AppTabbar: typeof import('./src/components/AppTabbar.vue')['default']
    CoverMosaic: typeof import('./src/components/CoverMosaic.vue')['default']
    EncryptedImage: typeof import('./src/components/EncryptedImage.vue')['default']
    HlsPlayer: typeof import('./src/components/HlsPlayer.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader.vue')['default']
    LineIcon: typeof import('./src/components/LineIcon.vue')['default']
    MediaGrid: typeof import('./src/components/MediaGrid.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionPanel: typeof import('./src/components/SectionPanel.vue')['default']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
